/**
 * Faux Spy Revenue Digest
 * Pulls last 7 days of Stripe data and posts a GitHub Issue with the summary.
 *
 * Usage: node scripts/revenue-digest.js
 * Required env: STRIPE_SECRET_KEY, GH_TOKEN (auto-set in GitHub Actions)
 */

'use strict';

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');
const Stripe = require('stripe');

const REPO = 'NinjaFromQueens/fauxspy-website';

function ghWithFile(args, body) {
  const tmp = path.join(os.tmpdir(), `revenue-${Date.now()}.md`);
  fs.writeFileSync(tmp, body, 'utf8');
  try {
    execSync(`gh ${args} --body-file "${tmp}" --repo ${REPO}`, { stdio: 'inherit' });
  } finally {
    fs.unlinkSync(tmp);
  }
}

function dollars(cents) {
  return `$${(cents / 100).toFixed(2)}`;
}

function planLabel(planId) {
  if (!planId) return 'unknown';
  if (planId.includes('video') && planId.includes('year')) return 'Video Yearly';
  if (planId.includes('video')) return 'Video Monthly';
  if (planId.includes('year')) return 'Pro Yearly';
  return 'Pro Monthly';
}

async function paginate(fn) {
  const items = [];
  let page = await fn({ limit: 100 });
  items.push(...page.data);
  while (page.has_more) {
    if (page.data.length === 0) break;
    page = await fn({ limit: 100, starting_after: items[items.length - 1].id });
    items.push(...page.data);
  }
  return items;
}

async function main() {
  if (!process.env.STRIPE_SECRET_KEY) {
    console.error('❌ STRIPE_SECRET_KEY is required');
    process.exit(1);
  }

  const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: '2025-05-28.basil' });

  const now = Math.floor(Date.now() / 1000);
  const weekAgo = now - 7 * 24 * 60 * 60;
  const today = new Date().toISOString().split('T')[0];

  console.log('📊 Pulling Stripe data...\n');

  // Active subscriptions
  const activeSubs = await paginate(params =>
    stripe.subscriptions.list({ ...params, status: 'active' })
  );
  console.log(`  Active subscriptions: ${activeSubs.length}`);

  // New subs this week
  const newSubs = activeSubs.filter(s => s.created >= weekAgo);

  // Cancellations this week
  const canceledSubs = await paginate(params =>
    stripe.subscriptions.list({ ...params, status: 'canceled', created: { gt: weekAgo } })
  );

  // Charges this week (gross revenue)
  const charges = await paginate(params =>
    stripe.charges.list({ ...params, created: { gt: weekAgo } })
  );
  const successfulCharges = charges.filter(c => c.paid && !c.refunded);
  const grossRevenue = successfulCharges.reduce((sum, c) => sum + c.amount, 0);

  // Refunds this week
  const refundTotal = charges
    .filter(c => c.amount_refunded > 0)
    .reduce((sum, c) => sum + c.amount_refunded, 0);

  // MRR — normalize each active sub to monthly
  let mrrCents = 0;
  const planCounts = {};
  for (const sub of activeSubs) {
    const item = sub.items?.data?.[0];
    if (!item) continue;
    const price = item.price;
    const amount = price.unit_amount || 0;
    const interval = price.recurring?.interval;
    const monthly = interval === 'year' ? Math.round(amount / 12) : amount;
    mrrCents += monthly;

    const label = planLabel(price.id || price.nickname || sub.metadata?.plan || '');
    planCounts[label] = (planCounts[label] || 0) + 1;
  }

  // Format plan breakdown
  const planRows = Object.entries(planCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([plan, count]) => `| ${plan} | ${count} |`)
    .join('\n');

  const netRevenue = grossRevenue - refundTotal;

  const body = `# Revenue Digest — ${today}

## This Week

| Metric | Value |
|--------|-------|
| Gross revenue (7d) | **${dollars(grossRevenue)}** |
| Refunds (7d) | ${dollars(refundTotal)} |
| Net revenue (7d) | **${dollars(netRevenue)}** |
| New subscriptions | ${newSubs.length} |
| Cancellations | ${canceledSubs.length} |
| Net new subs | ${newSubs.length - canceledSubs.length >= 0 ? '+' : ''}${newSubs.length - canceledSubs.length} |

## All-Time

| Metric | Value |
|--------|-------|
| Active subscriptions | **${activeSubs.length}** |
| Estimated MRR | **${dollars(mrrCents)}** |
| Estimated ARR | **${dollars(mrrCents * 12)}** |

## Active Subscriptions by Plan

| Plan | Count |
|------|-------|
${planRows || '| — | — |'}

---
*Generated by Faux Spy Revenue Digest · ${today}*`;

  console.log('\nPosting GitHub Issue...');
  ghWithFile(`issue create --title "Revenue Digest — ${today}"`, body);
  console.log('✅ Done.');
}

main().catch(err => {
  console.error('Revenue digest failed:', err.message);
  process.exit(1);
});
