/**
 * Faux Spy SEO Report Generator + Auto-Fixer
 * Reads seo-results.json, generates a markdown report, and applies safe technical fixes.
 *
 * Usage: node scripts/seo-report.js
 * Run after: node scripts/seo-agent.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

const SITE_ROOT = path.resolve(__dirname, '..');
const RESULTS_FILE = path.join(SITE_ROOT, 'seo-results.json');
const REPORT_FILE = path.join(SITE_ROOT, 'seo-report.md');
const FIXES_SUMMARY_FILE = path.join(SITE_ROOT, 'seo-fixes-summary.md');

if (!fs.existsSync(RESULTS_FILE)) {
  console.error('❌ seo-results.json not found. Run seo-agent.js first.');
  process.exit(1);
}

const results = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf8'));

// ─── Report Generator ─────────────────────────────────────────────────────────

function buildReport(results, fixesMade) {
  const today = new Date().toISOString().split('T')[0];
  const totalPages = results.length;
  const allIssues = results.flatMap(r => r.issues);
  const critical = allIssues.filter(i => i.severity === 'CRITICAL').length;
  const warnings = allIssues.filter(i => i.severity === 'WARNING').length;
  const info = allIssues.filter(i => i.severity === 'INFO').length;
  const clean = results.filter(r => r.issues.length === 0).length;

  let md = `# SEO Audit Report — ${today}\n\n`;
  md += `**${totalPages} pages audited** · 🔴 ${critical} critical · 🟡 ${warnings} warnings · ℹ️ ${info} info · ✅ ${clean} clean\n\n`;

  if (fixesMade.length > 0) {
    md += `> **Auto-fixes applied:** ${fixesMade.length} technical issue(s) were fixed automatically and are included in this PR.\n\n`;
  }

  // Summary table
  md += `## Summary\n\n`;
  md += `| Page | Critical | Warnings | Info |\n`;
  md += `|------|----------|----------|------|\n`;
  const sorted = [...results].sort((a, b) => {
    const aC = a.issues.filter(i => i.severity === 'CRITICAL').length;
    const bC = b.issues.filter(i => i.severity === 'CRITICAL').length;
    return bC - aC || b.issues.filter(i => i.severity === 'WARNING').length - a.issues.filter(i => i.severity === 'WARNING').length;
  });
  sorted.forEach(r => {
    const c = r.issues.filter(i => i.severity === 'CRITICAL').length;
    const w = r.issues.filter(i => i.severity === 'WARNING').length;
    const n = r.issues.filter(i => i.severity === 'INFO').length;
    const icon = c > 0 ? '🔴' : w > 0 ? '🟡' : '✅';
    md += `| ${icon} [${r.file}](${r.url}) | ${c || '—'} | ${w || '—'} | ${n || '—'} |\n`;
  });

  // Per-page details (only pages with issues)
  const withIssues = sorted.filter(r => r.issues.length > 0);
  if (withIssues.length > 0) {
    md += `\n## Issues by Page\n\n`;
    withIssues.forEach(r => {
      md += `### ${r.file}\n`;
      md += `URL: ${r.url}\n\n`;

      for (const sev of ['CRITICAL', 'WARNING', 'INFO']) {
        const group = r.issues.filter(i => i.severity === sev);
        if (group.length === 0) continue;
        const icon = sev === 'CRITICAL' ? '🔴' : sev === 'WARNING' ? '🟡' : 'ℹ️';
        group.forEach(issue => {
          const fixNote = issue.autoFix ? ' *(auto-fixed)*' : '';
          md += `- ${icon} **${issue.rule}**${fixNote}: ${issue.detail}\n`;
        });
      }
      md += '\n';
    });
  }

  // What to do next (content issues that need human attention)
  const contentIssues = allIssues.filter(i =>
    ['ai-writing-patterns', 'thin-content', 'missing-eeat', 'outdated-claims',
     'keyword-mismatch', 'duplicate-content-risk', 'heading-structure'].some(k => i.rule.includes(k) || i.rule.includes('content') || i.rule.includes('eeat') || i.rule.includes('ai-'))
  );
  if (contentIssues.length > 0) {
    md += `## Content Issues Requiring Manual Review\n\n`;
    md += `These cannot be auto-fixed — they require human rewriting:\n\n`;
    contentIssues.forEach(i => {
      const page = results.find(r => r.issues.includes(i));
      md += `- **${page?.file}** — ${i.rule}: ${i.detail}\n`;
    });
    md += '\n';
  }

  md += `---\n*Generated by Faux Spy SEO Agent · ${today}*\n`;
  return md;
}

// ─── Auto-Fixer ───────────────────────────────────────────────────────────────

function truncateAtWordBoundary(text, maxLen) {
  if (text.length <= maxLen) return text;
  const cut = text.lastIndexOf(' ', maxLen - 3);
  return (cut > 0 ? text.slice(0, cut) : text.slice(0, maxLen - 3)) + '...';
}

function applyFixes(results) {
  const fixLog = [];

  results.forEach(r => {
    const fixable = r.issues.filter(i => i.autoFix);
    if (fixable.length === 0) return;

    const absPath = path.join(SITE_ROOT, r.file);
    if (!fs.existsSync(absPath)) return;

    let html = fs.readFileSync(absPath, 'utf8');
    let changed = false;

    fixable.forEach(issue => {
      const { type, value, current } = issue.autoFix;

      if (type === 'add-canonical') {
        if (!html.includes('rel="canonical"')) {
          html = html.replace('</head>', `  <link rel="canonical" href="${value}">\n</head>`);
          fixLog.push({ file: r.file, rule: issue.rule, detail: `Added canonical: ${value}` });
          changed = true;
        }
      }

      if (type === 'add-og-url') {
        if (!html.includes('og:url')) {
          html = html.replace('</head>', `  <meta property="og:url" content="${value}">\n</head>`);
          fixLog.push({ file: r.file, rule: issue.rule, detail: `Added og:url: ${value}` });
          changed = true;
        }
      }

      if (type === 'truncate-meta-desc' && current) {
        const truncated = truncateAtWordBoundary(current, 160);
        if (truncated !== current) {
          const escaped = current.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
          const newHtml = html.replace(
            new RegExp(`(meta name="description" content=")${escaped}(")`),
            `$1${truncated}$2`
          );
          if (newHtml !== html) {
            html = newHtml;
            fixLog.push({ file: r.file, rule: issue.rule, detail: `Truncated meta description to ${truncated.length} chars` });
            changed = true;
          }
        }
      }

      if (type === 'strip-html-links') {
        const before = html;
        html = html.replace(/href="(\/[^"]*?)\.html"/g, 'href="$1"');
        if (html !== before) {
          fixLog.push({ file: r.file, rule: issue.rule, detail: `Removed .html extensions from internal links` });
          changed = true;
        }
      }

      if (type === 'add-empty-alt') {
        // Only add alt="" to img tags that have no alt attribute at all
        const before = html;
        html = html.replace(/<img(?![^>]*\balt=)([^>]*)>/gi, '<img$1 alt="">');
        if (html !== before) {
          fixLog.push({ file: r.file, rule: issue.rule, detail: `Added alt="" to img tags missing alt attribute` });
          changed = true;
        }
      }
    });

    if (changed) {
      fs.writeFileSync(absPath, html, 'utf8');
      console.log(`  ✏️  Fixed ${r.file} (${fixable.length} issue(s))`);
    }
  });

  return fixLog;
}

// ─── Fixes Summary ────────────────────────────────────────────────────────────

function buildFixesSummary(fixLog) {
  const today = new Date().toISOString().split('T')[0];
  let md = `# SEO Auto-Fixes — ${today}\n\n`;
  md += `${fixLog.length} technical issue(s) were automatically fixed:\n\n`;

  const byFile = {};
  fixLog.forEach(f => {
    if (!byFile[f.file]) byFile[f.file] = [];
    byFile[f.file].push(f);
  });

  Object.entries(byFile).forEach(([file, fixes]) => {
    md += `### ${file}\n`;
    fixes.forEach(f => { md += `- \`${f.rule}\`: ${f.detail}\n`; });
    md += '\n';
  });

  md += `---\n*Applied by Faux Spy SEO Agent · ${today}*\n`;
  return md;
}

// ─── Main ─────────────────────────────────────────────────────────────────────

console.log('📝 Faux Spy SEO Report Generator\n');

console.log('Applying auto-fixes...');
const fixLog = applyFixes(results);
console.log(`  ${fixLog.length} fix(es) applied\n`);

console.log('Building report...');
const report = buildReport(results, fixLog);
fs.writeFileSync(REPORT_FILE, report, 'utf8');
console.log(`  Report saved to seo-report.md`);

if (fixLog.length > 0) {
  const summary = buildFixesSummary(fixLog);
  fs.writeFileSync(FIXES_SUMMARY_FILE, summary, 'utf8');
  console.log(`  Fixes summary saved to seo-fixes-summary.md`);
}

// Export for GitHub Actions
if (process.env.GITHUB_OUTPUT) {
  fs.appendFileSync(process.env.GITHUB_OUTPUT, `has_fixes=${fixLog.length > 0}\n`);
}

console.log('\nDone.');
